# Generated by Django 5.1.7 on 2025-03-10 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')])),
            ],
            options={
                'verbose_name_plural': 'Productores',
            },
        ),
        migrations.CreateModel(
            name='ProductoControlFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ica', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.PositiveIntegerField(help_text='Frecuencia en días')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ultima_aplicacion', models.DateField()),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_control_fertilizante', to='viveros.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoControlHongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ica', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.PositiveIntegerField(help_text='Frecuencia en días')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodo_carencia', models.PositiveIntegerField(help_text='Período de carencia en días')),
                ('nombre_hongo', models.CharField(max_length=100)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_control_hongo', to='viveros.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoControlPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ica', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.PositiveIntegerField(help_text='Frecuencia en días')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodo_carencia', models.PositiveIntegerField(help_text='Período de carencia en días')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_control_plaga', to='viveros.labor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catastro', models.CharField(max_length=50, unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='viveros.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='viveros.finca')),
            ],
            options={
                'unique_together': {('finca', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='labor',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='viveros.vivero'),
        ),
    ]
